### ISSUE TITLE
Nested markup extensions don't seem to be acted on.

### ISSUE THREAD

**Issue by grokys** [SuperJMN/OmniXAML#50] opened 2015-10-25 13:03 UTC
If I have a nested markup extension like so:

    IsVisible="{TemplateBinding Path=IsFloatingWatermarkVisible, Converter={x:Type FooBar}}"

(see https://github.com/Perspex/Perspex/blob/xaml-control-themes/samples/XamlTestApplicationPcl/TextBox.paml#L22)

Then the nested `x:Type` markup extension seems to be ignored: in the example above there is no `FooBar` type in scope so I would expect an error, but instead nothing happens.

**Comment by SuperJMN** [comment] 2015-10-25 21:09
I'm looking into it! so far, I've created a test for the Markup Extensions parser and it parses it perfectly. The problem is somewhere else.

**Comment by SuperJMN** [comment] 2015-10-26 18:01
Hahaha, I found out that nested extensions are absolutely ignored, and with a reason! I'm fixing it.

**Comment by SuperJMN** [comment] 2015-10-26 18:13
Fixed with https://github.com/SuperJMN/OmniXAML/commit/99d24a3019504b901742496fffbdbb549a7245ab.

**Closed by SuperJMN** 2015-10-26 18:13 UTC

**Comment by grokys** [comment] 2015-10-26 20:38
Still not working for some reason...

**Comment by grokys** [comment] 2015-10-26 21:57
Oh no, my mistake - I was doing something stupid ;)
