### ISSUE TITLE
Add Support for Special Tokens (and Registered Token Handlers)

### ISSUE THREAD

**Issue by Michael-DST** [SuperJMN/OmniXAML#34] opened 2015-09-22 13:31 UTC
Please see this article: http://grokys.github.io/perspex/perspex-properties/

It would be great to get the tokens used in the initialization moved over to the Xaml parser, to leverage custom providers for a token value.  For example, in the case of:

```xml
Property="{{!Property.Foo[Property.Bar]}}"
```

This could get passed to the different registered token processors to see if they can handle it, and if so, return the value based on the string input.  As alluded to, numerous processors can be registered, so this is not a hard-coded value that is accounted for, but more of a framework that end developers can tie into to make this a much more powerful Xaml-parser than traditional parsers.

Additionally, some thought will have to be given towards the designer implications for this and ensure this is elegantly handled in the designers that render this value.

**Comment by grokys** [comment] 2015-09-23 17:38
There are two parts to this:

- A markup extension that uses the special syntax `{{foo}}`. This would have to be implemented by OmniXaml.
- Expressions in a binding. This wouldn't actually be an OmniXaml issue as the markup extensions are provided by Perspex itself.

As I mentioned in chat, I'm not fond of the idea of registering custom syntaxes - I'd prefer to use a subset of C# syntax, perhaps parsed by roslyn. There would be nothing stopping you however from creating your own markup extension to parse whatever syntax you may come up with.

**Comment by Michael-DST** [comment] 2015-09-23 17:42
Alright, I want to back up here to just to make sure that I understand things.  What makes this possible: `[!Property2] = anotherControl[!Property1]` ?

Is the ! a token that you register somehow to make the binding work?  If so -- and I assume it is because that does not look like something that should compile in C# -- that is the ask here.  Basically to enable parity between this new C#6.0 functionality and OmniXaml.

**Comment by grokys** [comment] 2015-09-23 17:45
That is in C#, not XAML. The `!` is C#'s negation operator.

**Comment by Michael-DST** [comment] 2015-09-23 18:13
I understand it is in C#, but the point here is that there appears to be some clever token implementation that initializes some binding between properties, is this correct?  Based on the description of the article, it appears that the "!" does not negate in the case, but establishes bindings between two properties.  Is that correct?  If so, then that is what we are after here in Xaml (with *any* token that is configured by a registered token processor, not just from something we got from this new C# cleverness -- that is, it doesn't have to be C# related).  If not, then I have completely misunderstood all of this. :P 

However, it does seem that you can do two-way binding with "!!" with the example after the one I pasted above which seems to be a double-negation?  Doesn't make sense from a typical .NET perspective,   So that is why I am going down this road.

**Comment by grokys** [comment] 2015-09-25 00:42
I'm still not sure what you mean, but the stuff you're talking about isn't related to OmniXaml in any way - it was simply as feature to allow bindings and attached properties to be set from object initializers in C#.

**Comment by Michael-DST** [comment] 2015-09-25 00:47
Right, and the request here is to make it related to OmniXaml by enabling that same cool initialization functionality in Xaml. :)  What I am trying to say is that cool initialization tokens like those shouldn't be captive to strictly C# if you can help it.  To be sure, I am not completely/dogmatically tied to this, but just trying to help out OmniXaml and its overall value proposition.  I guess I should look into how you enabled those initializers to get better context and to better articulate what I am trying to say.  But, please feel free to close this issue if you do not feel it is congruent with the spirit/goals here.

**Comment by grokys** [comment] 2015-09-25 00:50
It's just that XAML already has syntax for binding: `{Binding Foo}`. I think the problem is that I don't understand what exactly you are proposing. If you could give some examples then that might help.

**Comment by Michael-DST** [comment] 2015-09-25 00:53
OK, fair enough.  Let me do some research on this and I will have something more definitive.  Hopefully by the end of this weekend.

**Comment by Michael-DST** [comment] 2015-09-25 18:21
OK, the magic happens in an operator registration [like this one](https://github.com/Perspex/Perspex/blob/master/src/Perspex.Base/PerspexProperty.cs#L170).  Here, you can define any arbitrary token (or set of tokens) to perform an action during object serialization.

That's the gist of the ask here, basically infrastructure that allows you to do the same thing in Xaml.  The net result could be a shortcut to a markupextension or whatever the action assigned to the token might do. This would cut down on verbosity along with providing some coolness factor (that, incidentally, has been migrated from C#6.0).

I was also confused in my initial post in that I thought the "!" was a special token, but its intent is actually meant to be an evaluated expression on a boolean property, doh.

I agree this is ambitious and probably isn't something to aim for in a pre-1.0 product.  I just really like the idea of this. :)  Also, designer-considerations are pretty challenging.  _Very_ challenging. It would be nice to put this on a future list (probably WAY future), but I have no problems closing this for now as long as it is something that is in the background going forward if that is what you agree to as well.

Thank you for the dialogue here!

**Comment by SuperJMN** [comment] 2015-11-10 09:58
Michael, this will not be implemented in the near future. I'm closing this issue. It's a low priority right now. It seems Perspex does what you say with its own mechanism.

**Closed by SuperJMN** 2015-11-10 09:58 UTC

**Comment by Michael-DST** [comment] 2015-11-10 10:01
Cool... yeah, at this point it might be a little ambitious.  After all, it took 6 versions of C# before it was available there. :)  Thanks for the consideration and discussion!
